In [ ]:
import numpy as np

In [5]:
a=[0,1,2,3,4,5,6,7,8,9]
print(np.array(a))

NameError: name 'np' is not defined

In [2]:
print(np.zeros(10))

NameError: name 'np' is not defined

In [3]:
b=np.zeros((5,10))
print(b)

NameError: name 'np' is not defined

In [13]:
print(np.ones(5))

[1. 1. 1. 1. 1.]


In [15]:
print(np.ones((5,5)))

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [17]:
print(np.eye(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [18]:
print(np.arange(0,10))

[0 1 2 3 4 5 6 7 8 9]


In [19]:
print(np.linspace(2,10,5))

[ 2.  4.  6.  8. 10.]


In [20]:
print(np.full(5,9))

[9 9 9 9 9]


In [21]:
print(np.full((9,2),5))

[[5 5]
 [5 5]
 [5 5]
 [5 5]
 [5 5]
 [5 5]
 [5 5]
 [5 5]
 [5 5]]


In [22]:
print(np.random.rand(5,9))

[[0.48150235 0.26126259 0.50404118 0.92618224 0.16406075 0.6585412
  0.05820654 0.38828077 0.77825039]
 [0.00985445 0.1877123  0.05457158 0.85933414 0.43303096 0.59659554
  0.14901442 0.48998176 0.89098844]
 [0.43652622 0.99312696 0.82630793 0.52982515 0.98759447 0.73058619
  0.58287433 0.97070137 0.09350556]
 [0.57782071 0.80488924 0.18484517 0.09695366 0.86624721 0.33581588
  0.99294048 0.29884788 0.93243201]
 [0.75100438 0.73395457 0.17607696 0.99876225 0.46116548 0.4478777
  0.21688173 0.09908629 0.30530371]]


In [23]:
print(np.random.rand(6))

[0.34863857 0.35015582 0.69348698 0.35253427 0.22874828 0.10284595]


In [25]:
print(np.random.randint(6))

4


In [29]:
print(np.random.randint(5,9))

8


In [30]:
print(np.random.randint(2,10,5))

[2 5 9 5 7]


In [31]:
print(np.random.randint(2,10,(5,6)))

[[9 5 2 7 6 7]
 [7 8 5 5 3 8]
 [5 7 2 3 4 5]
 [2 5 4 5 6 3]
 [9 9 5 9 2 5]]


In [4]:
b=np.arange(1,11)
print(b)

NameError: name 'np' is not defined

In [2]:
h=np.array([[1,4,5],[4,7,2],[2,3,9]])
print(h)

NameError: name 'np' is not defined

In [3]:
print(b[5])

NameError: name 'b' is not defined

In [6]:
print(h[2][1])

NameError: name 'h' is not defined

In [7]:
print(b[1:9:2])

NameError: name 'b' is not defined

In [8]:
print(h[0:2,1:])

NameError: name 'h' is not defined

In [9]:
b.shape()

NameError: name 'b' is not defined

In [10]:
h.shape()

NameError: name 'h' is not defined

In [11]:
b.size()

NameError: name 'b' is not defined

In [12]:
h.size()

NameError: name 'h' is not defined

In [13]:
b.dtype()

NameError: name 'b' is not defined

In [14]:
h.dtype()

NameError: name 'h' is not defined

In [15]:
print(np.sqrt(b))

NameError: name 'np' is not defined

In [16]:
print(np.sqrt(h))

NameError: name 'np' is not defined

In [17]:
g=np.arange(11,21)
print(g)

NameError: name 'np' is not defined

In [18]:
j=np.array([[1,4,5],[4,7,2],[2,3,9]])
print(j)

NameError: name 'np' is not defined

In [19]:
g+b

NameError: name 'g' is not defined

In [20]:
h+j

NameError: name 'h' is not defined

In [21]:
g*b

NameError: name 'g' is not defined

In [22]:
h*j

NameError: name 'h' is not defined

In [23]:
g/b

NameError: name 'g' is not defined

In [24]:
h/j

NameError: name 'h' is not defined