In [1]:
import numpy as np

In [4]:
a1=np.arange(1,11)
print(a1)

[ 1  2  3  4  5  6  7  8  9 10]


In [5]:
a2=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
b1=np.arange(21,31)
print(b1)

[21 22 23 24 25 26 27 28 29 30]


In [7]:
b2=np.array([[11,12,13],[14,15,16],[17,18,19]])
print(b2)

[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [8]:
print(np.concatenate((a1,b1)))

[ 1  2  3  4  5  6  7  8  9 10 21 22 23 24 25 26 27 28 29 30]


In [9]:
print(np.vstack((a2,b2)))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]


In [10]:
print(np.hstack((a2,b2)))

[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]


In [11]:
print(a2.flatten())

[1 2 3 4 5 6 7 8 9]


In [12]:
print(b2.flatten())

[11 12 13 14 15 16 17 18 19]


In [13]:
print(a2.ravel())

[1 2 3 4 5 6 7 8 9]


In [14]:
print(b2.ravel())

[11 12 13 14 15 16 17 18 19]


In [15]:
print(a2.reshape(9))

[1 2 3 4 5 6 7 8 9]


In [16]:
print(b2.reshape(9))

[11 12 13 14 15 16 17 18 19]


In [20]:
print(a1)
print(b1)
print(a2)
print(b2)

[ 1  2  3  4  5  6  7  8  9 10]
[21 22 23 24 25 26 27 28 29 30]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [21]:
print(np.split(a1,2))

[array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10])]


In [33]:
print(np.hsplit(a2,3))

[array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]


In [45]:
print(np.vsplit(a2,3))

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]


In [49]:
c1=np.array([1,2,3,4,1,2,5,6,8,2,8,1])
print(c1)

[1 2 3 4 1 2 5 6 8 2 8 1]


In [50]:
print(np.where(c1==1))

(array([ 0,  4, 11]),)


In [51]:
c2=np.array([[1,4,2],[2,5,4],[1,4,7]])
print(c2)

[[1 4 2]
 [2 5 4]
 [1 4 7]]


In [52]:
print(np.where(c2==4))

(array([0, 1, 2]), array([1, 2, 1]))


In [53]:
print(np.where(c2==7))

(array([2]), array([2]))


In [54]:
print(np.sort(c1))

[1 1 1 2 2 2 3 4 5 6 8 8]


In [55]:
print(np.sort(c2))

[[1 2 4]
 [2 4 5]
 [1 4 7]]


In [64]:
print(np.sort(c2,axis=0))

[[1 4 2]
 [1 4 4]
 [2 5 7]]


In [66]:
print(np.sort(c2,axis=1))

[[1 2 4]
 [2 4 5]
 [1 4 7]]


In [69]:
print(np.sort(c1)[::-1])

[8 8 6 5 4 3 2 2 2 1 1 1]


In [71]:
print(c2)

[[1 4 2]
 [2 5 4]
 [1 4 7]]


In [74]:
print(np.sort(c2,axis=0)[::-1])

[[2 5 7]
 [1 4 4]
 [1 4 2]]


In [78]:
print(np.sort(c2,axis=1)[::-1])

[[1 4 7]
 [2 4 5]
 [1 2 4]]


In [79]:
print(np.sum(c1))
print(np.sum(c2))

43
30


In [81]:
print(np.mean(c1))
print(np.mean(c2))

3.5833333333333335
3.3333333333333335


In [82]:
print(np.median(c1))
print(np.median(c2))

2.5
4.0


In [84]:
print(np.max(c1))
print(np.max(c2))

8
7


In [85]:
print(np.min(c1))
print(np.min(c2))

1
1


In [86]:
print(np.std(c1))
print(np.std(c2))

2.4986107250941583
1.8856180831641267


In [87]:
print(np.var(c1))
print(np.var(c2))

6.2430555555555545
3.5555555555555554


In [88]:
print(c2)

[[1 4 2]
 [2 5 4]
 [1 4 7]]


In [89]:
print(np.sum(c2,axis=1))
print(np.sum(c2,axis=0))

[ 7 11 12]
[ 4 13 13]


In [90]:
print(np.mean(c2,axis=1))
print(np.mean(c2,axis=0))

[2.33333333 3.66666667 4.        ]
[1.33333333 4.33333333 4.33333333]


In [91]:
print(np.median(c2,axis=1))
print(np.median(c2,axis=0))

[2. 4. 4.]
[1. 4. 4.]


In [92]:
print(np.max(c2,axis=1))
print(np.max(c2,axis=0))

[4 5 7]
[2 5 7]


In [93]:
print(np.min(c2,axis=1))
print(np.min(c2,axis=0))

[1 2 1]
[1 4 2]


In [94]:
print(np.std(c2,axis=1))
print(np.std(c2,axis=0))

[1.24721913 1.24721913 2.44948974]
[0.47140452 0.47140452 2.05480467]


In [95]:
print(np.var(c2,axis=1))
print(np.var(c2,axis=0))

[1.55555556 1.55555556 6.        ]
[0.22222222 0.22222222 4.22222222]
