In [1]:
import numpy as np

In [2]:
ages=np.array([25,30,18,35,22,40,17])
print(ages)

[25 30 18 35 22 40 17]


In [3]:
adults=np.array([ages>=18])
print(adults)

[[ True  True  True  True  True  True False]]


In [4]:
adults=np.ma.array(ages,mask=[ages<18])
print(adults)

[25 30 18 35 22 40 --]


In [12]:
young_adults=np.array((ages>20) & (ages<35))
print(young_adults)

[ True  True False False  True False False]


In [13]:
name=np.array(['alice','bob','charlie','david','eve'])
print(name)

['alice' 'bob' 'charlie' 'david' 'eve']


In [28]:
print(name[(np.char.startswith(name,'a'))|(np.char.startswith(name,'e'))])

['alice' 'eve']


In [35]:
tempratures=np.array([28,32,25,35,30,22,38])
print(tempratures)

[28 32 25 35 30 22 38]


In [36]:
is_hot=np.ma.array(tempratures,mask=[tempratures<30])
print(is_hot)

[-- 32 -- 35 30 -- 38]


In [39]:
is_hot=np.array(tempratures>=30)
print(is_hot)

[False  True False  True  True False  True]


In [42]:
tempratures[tempratures>30]=31
print(tempratures)

[28 31 25 31 30 22 31]


In [43]:
scores=np.array([65,80,72,90,55,78])
print(scores)

[65 80 72 90 55 78]


In [49]:
grades=np.where(scores>=75,'pass','fail')
print(grades)

['fail' 'pass' 'fail' 'pass' 'fail' 'pass']


In [51]:
numbers_1d=np.arange(1,13)
print(numbers_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [54]:
numbers_2d=numbers_1d.reshape(3,4)
print(numbers_2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [55]:
numbers_2d.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [56]:
values=np.arange(1,16)
print(values)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [57]:
values.reshape(5,-1)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [58]:
prices=np.array([10,20,30])
print(prices)

[10 20 30]


In [59]:
print(prices+5)

[15 25 35]


In [60]:
sales=np.array([[10,20],[15,25],[12,18]])
print(sales)

[[10 20]
 [15 25]
 [12 18]]


In [63]:
bonuses=np.array([[2],[3],[1]])
print(bonuses)

[[2]
 [3]
 [1]]


In [64]:
print(sales+bonuses)

[[12 22]
 [18 28]
 [13 19]]


In [65]:
tax_rates=np.array([0.1,0.05])
print(tax_rates)

[0.1  0.05]


In [66]:
print(sales*tax_rates)

[[1.   1.  ]
 [1.5  1.25]
 [1.2  0.9 ]]
